- name: nginx and updating
  apt:
    name: nginx
    state: latest

- name: replace the with my copy
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes






