- name: nginx and updating
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: replacing html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

