- name: nginx and updating
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: replace the with my copy
  ansible.builtin.copy:
    src: roles/nginx/files/default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes


