- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
    container_default_behavior: no_defaults
