{
 "title": "MySQL",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "io",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sql",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "server ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "read only",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Database Slects per minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "Select"
    }
   ]
  }
 ]
}