- name: iptables-persistent 
  apt:
    name: iptables-persistent 

- name: Agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download agama application
  ansible.builtin.get_url:
    dest: /opt/agama/Dockerfile
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    mode: "755"
  register: agama_installed

- name: iptables-save -t mangle
  shell: iptables-save -t mangle
  when: agama_installed.changed

- name: /var/local/iptables.mangle
  template:
    src: iptables.mangle.j2
    dest: /var/local/iptables.mangle
  when: agama_installed.changed

- name: Perform iptables-restore
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle
  when: agama_installed.changed

- name: agama Dependencies check and instalation
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql
    state: present

- name: Create agama image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Install agama docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: agama-{{item}}
    image: agama
    published_ports: "{{ agama_port + item | int }}:8000"
    restart_policy: always
    env:
        AGAMA_DATABASE_URI: mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}
  loop:
    - 1
    - 2