- name: Create a directory
  file:
    path: /home/backup/influxdb
    state: directory
    mode: "0700"
    owner: backup
    group: backup

- name: create a file influxdb-backup
  template:
    src: influxdb-backup
    dest: /etc/cron.d/influxdb-backup
