---
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://DennisBykov-2:9090/prometheus
    password:
    user:
    database:
    isDefault: true
    version: 1
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://DennisBykov-1:8086
    database: latency
    version: 1
    editable: false

  - name: InfluxDB-telegraf
    type: influxdb
    access: proxy
    orgId: 1
    url: http://DennisBykov-1:8086
    database: telegraf
    version: 1
    editable: false
