---
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://DennisBykov-2:9090/prometheus
    password:
    user:
    database:
    isDefault: true
    version: 1
    editable: false

