- name: install prometheus node exporters
  apt:
    name: prometheus-node-exporter
    state: latest
  register: node_exporter_installed

- name: prom_node_exp is started
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: 10 sec pause
  pause:
    seconds: 10
  when: node_exporter_installed.changed
