- name: Install fping
  ansible.builtin.apt:
    name: fping
    state: present

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present

- name: User pinger
  ansible.builtin.user:
    name: pinger

- name: Add pinger script
  ansible.builtin.template:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: '0555'
    owner: pinger
  notify: Restart pinger

- name: Creating pinger service
  ansible.builtin.template:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
  notify:
    - Restart pinger
    - Daemon_reload

- name: Create directory for pinger config
  ansible.builtin.file:
    path: /etc/pinger
    state: directory

- name: Adding config for pinger
  ansible.builtin.template:
    src: pinger.conf
    dest: /etc/pinger/pinger.conf
  notify: Restart pinger

- name: pinger started
  ansible.builtin.service:
    name: pinger
    state: started
    enabled: yes
