- name: Stop systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Change resolv.conf
  template:
    src: resolv.conf.j2 
    dest: /etc/resolv.conf
