
- name: Install docker container
  ansible.builtin.apt:
    name: 
      - docker.io
      - python3-docker
    state: present

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{docker_user}}"
    password: "{{grafana_pass}}"

- name: Docker started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
