- name: Install docker container
  ansible.builtin.apt:
    name: 
      - docker.io
      - python3-docker
    state: present

- name: Docker started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
